name: conda_env_d4z4ling
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12.13
  - samtools=1.22.1
  - bedtools=2.31.1
  - minimap2=2.28
  - seqtk=1.5
  - blast=2.17.0
  - seqkit=2.13.0
  - minimod=0.4.0
  - meryl=1.4.1
  - winnowmap=2.03
  - ucsc-blat=482
  - ucsc-psltobed=482
  - ucsc-bedgraphtobigwig=482
  - pip:
    - biopython==1.81
    - numpy==2.5.1
    - pandas==3.0.3
    - plotly==6.8.0
    - pysam==0.24.0
    - scipy==1.18.0
